### ISSUE TITLE
Intégration avec authentification d'Ademe

### ISSUE THREAD

**Issue by hfroot** [datagir/bilansclimatsimplifies#10]
- [x] Contacter ademe pour discuter l'approche, partager client id et urls
- [x] Front : envoyer utilisateur vers ademe page de connexion quand on veut connecter
- [x] Front : créer une page de redirection qui envoie le token dans le param vers notre API et attends un token en retour
- [x] Back : créer une API endpoint qui lit le token au format JWT avec les données d'utilisateur. Mettre à jour ou créer un utilisateur dans notre BDD. Répond avec un token.
- [x] Front : envoie le token dans l'en tête `Authorization` dans les requêtes API subséquentes.

**Comment by Clem-mrtn** [comment]
A relancer

**Comment by martinregner** [comment]
Fait

**Comment by florianpanchout** [comment]
@hfroot Est ce que le endpoint `ademeUser` me renverra à terme les infos user ? Ou on l'utilise juste pour créer un user ?

**Comment by hfroot** [comment]
@florianpanchout oui il peut, on a toujours le endpoint /user qui donne les infos sur l'utilisateur, mais si c'est plus pratique pour toi je peux retourner les infos avec /ademeUser - est-ce que tu préfères ça ?

**Comment by florianpanchout** [comment]
Est ce que les deux ne font pas doublon ? Est ce qu'on pourrait avoir seulement `user` avec `POST` pour créer et `GET` pour récupérer ?

Si j'ai bien compris le mécanisme en place, `/ademeUser` est appelé en POST à chaque login, indépendamment que l'utilisateur existe déjà en base ou non ?

**Comment by hfroot** [comment]
@florianpanchout oui - j'ai fait ça en pensant que à l'avenir peut-être il y aura des autres options d'auth mais c'est trop tôt pour ça, alors je suis d'acc que maintenant c'est un doublon. Je suis d'acc avec ta suggestion qu'on garde seulement /user avec un POST et GET. 
L'endpoint est appeler même si l'utilisateur existe car les données peuvent changer alors le POST met à jour l'utilisateur si il existe déjà
Tu veux que le POST revoie les données en réponse pour éviter un deuxième appel ?

**Comment by hfroot** [comment]
@florianpanchout `/ademeUser` accepte GET maintenant 👍 . Le valeur `isStaff` décide qui peut accéder `/export`

**Comment by florianpanchout** [comment]
> Tu veux que le POST revoie les données en réponse pour éviter un deuxième appel ?

Nope, pas besoin. J'invalide la query à chaque mutation et refais donc un GET. Ça fait un appel de plus mais ça simplifie énormément le code
