### ISSUE TITLE
Bug chargement de la page

### ISSUE THREAD

**Issue by martinregner** [datagir/bilansclimatsimplifies#11]
Au hasard d'une discussion, un contact m'indiquait que le site ne s'affichait pas pour lui

![bug bcs](https://user-images.githubusercontent.com/46482115/142024388-fd956e09-a473-4dff-9fb1-c362b4e0960e.png)

![bug bcs-log](https://user-images.githubusercontent.com/46482115/142024514-55d4e4c6-117a-4a31-8f6d-d1898ea7e8de.png)

**Comment by florianpanchout** [comment]
Est ce que ce ne serait pas une histoire de pare feu d'entreprise ?

**Comment by florianpanchout** [comment]
@martinregner sauf nouvelle info, je pense que l'on peut considérer qu'il s'agit d'un problème de pare feu. Le site actuellement en ligne est tellement simple que je ne vois pas d'ou pourrait venir une erreur comme ça
