### ISSUE TITLE
Recette v0.0.1

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/bilansclimatsimplifies#12]
Je te fais ici mes retours suite à ma recette de l'outil.
Il y a pas mal de choses que j'ai remonté mais qui ne sont juste pas encore développées, j'imagine en lien avec le back :  

**Homepage** 
- [x] Bouton _"S'inscrire"_ ? 
- [x] Bouton _"Connexion Admin"_ dans la barre du haut pour l'admin 
- [x] L'adresse mail contact  "centrederessourcesges@ademe.fr" => à intégrer dans le footer ?
- [ ] Il manque le compteur avec le nombre de Bilan **=> v2** ?

**Page : compte utilisateur :** 
- [x]  On a seulement **"Mes Bilans"** sur sa page utilisateur : est-ce qu'on reprendrait pas quelques informations d'identités du compte ? 

**Page : Mes Bilans**
- [x] Quand on clique sur un de ses bilans on a la case à cocher _"J'ai déjà fait mon Bilan"._ Je comprends pas trop à quoi elle sert ? Si je souhaite éditer mon bilan je peux cliquer sur le bouton _"Editer"_ et sinon je veux peux _"Supprimer"_ mon bilan
- [x] Ce serait bien d'avoir une distinction **"Mes Bilans"** & **"Mes Brouillons"** 

**Page : J'ai déjà fait mon Bilan** 
- [x] Une fois que j'ai renseigné post 1 & 2, **il manque un bouton** _"Enregistrer"_, bizarre d'avoir un bouton _"Editer"_ directement. 

**Page : Ajouter un Bilan** 
- [ ] Spécifier les messages d'erreur : aujourd'hui on a qu'un message d'erreur quand on remplit mal un champs. Mieux définir les messages d'erreur (_Un bilan existe déjà, erreurs de caractères pour les années, erreur SIREN il faut 9 chiffres etc._)

**Page : Post 1 & 2 :** 
- [x] Post 1 : Les FE ne sont pas triés par "les + utilisés" (Fioul domestique, fioul lourd, Gaz nat mix moyen, granule bois, plaquettes forestières) puis le reste 
- [x] Post 2 : les FE, ne sont pas séparés en _mode routier_ puis autre _mode de transport_ 
- [x] Rajouter un bouton "_Enregistrer_" : même si le bilan est enregistré automatiquement, l'utilisateur ne le sait pas forcément. Et c'est plus intuitif en tant qu'user de pouvoir enregistrer soit même. 
- [x] Rajouter dans les petits _"i"_ les définitions des posts 1 & 2

**Page résultat**
- [x] J'organiserai la page : Encart Post 1 + Encart Post 2 et en dessous le message encadré **"Votre bilan est publié"** 
- [x] Je comprends aujourd'hui qu'à la fin du post 2 on valide le bilan et qu'on arrive sur une page de récap. 
Mais j'ai buggué dans le parcours utilisateur,  je comprenais pas quand on arrivait sur la page de résultat qu'on ait pas un bouton _"Enregistrer"_ ou _"Valider le Bilan"_ avec le recap des données post 1 & post 2. 
**On pourrait soit :** 
        -  Soit rajouter un écran entre les deux pages où on a recap post 1 & 2 + bouton valider et au clique on arriverait sur l'écran de résultat avec bouton _Exporter le bilan en PDF_ + bouton _"Télécharger les calculs en .csv"_  
        - Soit avoir la page de résultat avec bouton "Valider le Bilan" => actualisation de la page avec le message encadré **"Votre bilan est publié"** + apparition des boutons  _"Exporter le bilan en PDF"_ + bouton _"Télécharger les calculs en .csv"_  
- [ ] Rajouter une flèche "Précédente" pour revenir au post 2 si besoin ?

**Comment by martinregner** [comment]
**Page de description de la société**
J'ai eu un message :
![image](https://user-images.githubusercontent.com/46482115/143421720-5e734468-dc30-4f3b-baae-91acaad2187e.png)
Sans s

**Comment by martinregner** [comment]
En complément : 

**Homepage**
Intégrer en effet dans le footer un formulaire de contact avec : 
Nom * 
Courriel *
Message *

et qui envoie automatiquement ce message à centrederessourcesges@ademe.fr avec pour sujet "Article 244 – Bilans Climat Simplifiés"

**Page : Ajouter un Bilan**
- le nombre de salariés – vérifier qu’il s’agit d’un nombre inférieur strictement à 500, ou à 250 pour les DOM  ; si limite dépassée (500 ou + / 250 ou +), afficher un message :
> Les entreprises de plus de 500 salariés (250 dans les DOM) sont dans l'obligation de réaliser un bilans d’émissions de gaz à effet de serre. [En Savoir + ](https://www.bilans-ges.ademe.fr/fr/accueil/contenu/index/page/art75/siGras/1)

- le numéro SIREN de l’entreprise – vérifier le format du numéro rentré ([formule de Luhn](https://portal.hardis-group.com/pages/viewpage.action?pageId=120357227))
- la section de la nomenclature des activités françaises (NAF rév.2) dans laquelle ils s’inscrivent - proposer une liste déroulante à partir de la [liste INSEE](https://www.insee.fr/fr/information/2120875) à jour (88 divisions)
- la région dans laquelle elles ont leur siège ou leur principal établissement – proposer une liste déroulante avec les 18 régions françaises (métropole et outre-mer)
- l’année de reporting du Bilan Climat Simplifié – deux vérifications à faire : 
 1) que l’année entrée est inférieure ou égale à l’année en cours --> un menu déroulant *année en cours -> 2019* peut peut-être simplifier les choses ?
 2) qu’il n’y a pas déjà en base de données un Bilan pour ce numéro SIREN et cette année de reporting.

**Comment by florianpanchout** [comment]
> Quand on clique sur un de ses bilans on a la case à cocher "J'ai déjà fait mon Bilan". Je comprends pas trop à quoi elle sert ? Si je souhaite éditer mon bilan je peux cliquer sur le bouton "Editer" et sinon je veux peux "Supprimer" mon bilan

@Clem-mrtn c'est pour ceux qui ont déjà fait leur bilan et souhaitent juste remplir le total de chaque poste. Qu'est ce qui te gène dans l'UX ? (en dehors du fait qu'il manque des textes d'explication et que la page du bilan n'est pas claire du tout pour l'instant). Est ce qu'il faudrait que je rajoute une étape intermédiaire après que l'on ai choisi "J'ai déjà fait mon bilan" ou l'on nous demande le total de chaque poste ?

**Comment by florianpanchout** [comment]
> Mais j'ai buggué dans le parcours utilisateur, je comprenais pas quand on arrivait sur la page de résultat qu'on ait pas un bouton "Enregistrer" ou "Valider le Bilan" avec le recap des données post 1 & post 2.

Tu cliques sur "Valider mon bilan" pour arriver la, et un message "Votre bilan est publié" sur la page. Ça ne suffit pas ?

**Comment by Clem-mrtn** [comment]
Je peux pas plus me connecter avec les comptes de test, mais : 
- Oui effectivement j'avais trouvé ça confusant d'avoir cette petit case à cocher, puisqu'en fait t'es déjà sur la page où tu peux rentrer juste tes résultats si tu as déjà fait ton bilan. Du coup je comprends pas son utilité ?
- En fait, une fois que t'as compris la navigation, ça va. Mais j'avoue que c'est pas très intuitif dans le parcours, j'ai un peu galéré pour ma première simulation 😆 C'est pour ça que je proposais d'intégrer un écran intermédiaire où on a le recap post 1 & 2 un bouton Valider et on garde l'écran de fin tel quel 

**=> on peut s'en reparler demain au stand up et refaire la simu** ?

**Comment by florianpanchout** [comment]
> Oui effectivement j'avais trouvé ça confusant d'avoir cette petit case à cocher, puisqu'en fait t'es déjà sur la page où tu peux rentrer juste tes résultats si tu as déjà fait ton bilan. Du coup je comprends pas son utilité ?

La checkbox permet de passer entre ces deux modes justement. Si elle est décochée, "Éditer le poste" renvoie vers la liste d'émission du poste. Si elle est cochée, "Éditer le poste" permet de modifier le total directement.

 Je suis d'accord que c'est incompréhensible pour l'instant, mais je coince un peu pour améliorer ce workflow (en dehors de mettre un meilleurs wording). Est ce qu'on veut laisser à l'utilisateur la possibilité de modifier son choix (j'ai déjà fait / je n'ai pas déjà fait) par la suite ? Si non, on s'évite cette question

**Comment by florianpanchout** [comment]
J'ai créé 3 issues  (#19, #20 , #15) avec ce qu'il reste à faire de cette issue. Tout le reste devrait être traité normalement
