### ISSUE TITLE
Export public

### ISSUE THREAD

**Issue by hfroot** [datagir/bilansclimatsimplifies#13]
Integration avec https://data.ademe.fr/
https://koumoul.com/en/documentation/developer

Export des bilans qui sont publiés.

Données :

Raison sociale
SIREN
Nombre salariés
Région
NAF
Année
Date de publication
Résultat poste 1
Résultat poste 2
Total

**Comment by hfroot** [comment]
@martinregner est-ce que tu peux confirmer la liste de données au-dessus et me mettre en contact avec la personne chez koumoul ?

**Comment by hfroot** [comment]
@martinregner quel fréquence de MAJ de données est-ce que tu veux avoir pour l'export public ? Par exemple - chaque jour/semaine/modification ?

**Comment by martinregner** [comment]
Soit 1 fois par jour et soit à chaque modif (si pas plus complexe selon l'API utilisée).
Qu'en penses-tu ?

**Comment by hfroot** [comment]
> Soit 1 fois par jour et soit à chaque modif (si pas plus complexe selon l'API utilisée). Qu'en penses-tu ?

Je pense que ça sera plus stable et moins complexe de le faire une fois par jour - on ne doit pas penser trop du cas où il y aura un échec de connexion (car toutes les données sont présentes dans le fichier quotidienne), et l'export bulk me semble plus utilisé après l'appel avec Koumoul

**Comment by hfroot** [comment]
@martinregner j'ai écrit le code pour export public. Pour l'instant je fais la connexion avec un API privé sur mon compte personnel chez Koumoul - est-ce qu'il y a une compte organisationnel pour datagir ou ademe que tu veux que j'utilise ?

![Screenshot 2021-12-09 at 14 52 55](https://user-images.githubusercontent.com/9282816/145408959-867c5dbd-b94c-41f5-8b2c-e0002af3ac51.png)

**Comment by florianpanchout** [comment]
Traité ici : https://github.com/datagir/bilansclimatsimplifies/issues/24
