### ISSUE TITLE
Export privé

### ISSUE THREAD

**Issue by hfroot** [datagir/bilansclimatsimplifies#14]
Format CSV

Garder par un login et ne pas gérer avec Ademe connect. Les utilisateurs qui veulent utiliser cette fonctionnalité doivent utiliser un compte créer par un membre de l'équipe datagir.

Export de tous les bilans, publiés ou non.

Données (champs en gras qui ne sont pas inclus dans l'export public #13) :

**Prénom et nom du déposant
Email du gestionnaire**
Raison sociale
SIREN
Nombre salariés
Région
NAF
Année
**Statut (brouillon/publié)**
**Date de création**
Date de publication
**Mode (calculs faits par un total d’émissions ou manuellement)**
Résultat poste 1
Résultat poste 2
Total

**Comment by hfroot** [comment]
@martinregner est-ce que tu peux confirmer les infos au-dessus ? 
Je vois dans le trame qu'il y avait l'idée d'un export d'inscrites - est-ce que c'est toujours pértinant ?

**Comment by martinregner** [comment]
C'est exactement ça 👍 
Juste, sur ces deux points :

> Garder par un login et ne pas gérer avec Ademe connect. Les utilisateurs qui veulent utiliser cette fonctionnalité doivent utiliser un compte créer par un membre de l'équipe datagir.

Pas possible de garder ADEME connect et de dire en base quel est l'utilisateur qui peut être admin ?

> Je vois dans le trame qu'il y avait l'idée d'un export d'inscrites - est-ce que c'est toujours pértinant ?

En effet, c'est peu pertinent : pour avoir cela il suffit de regarder les premières colonnes de l'export complet

**Comment by hfroot** [comment]
> Pas possible de garder ADEME connect et de dire en base quel est l'utilisateur qui peut être admin ?

C'est possible, même mieux, si tous les utilisateurs vont s'authentifier avec ademe. Qui va gérer les droits d'accès ?

Qu'est-ce que tu penses de ce format [bilans_climat_simplifies_2021-12-03.csv](https://github.com/datagir/bilansclimatsimplifies/files/7651159/bilans_climat_simplifies_2021-12-03.csv) ?

**Comment by martinregner** [comment]
> C'est possible, même mieux, si tous les utilisateurs vont s'authentifier avec ademe. Qui va gérer les droits d'accès ?

Ok top !
C'est Fanny qui dira qui doit être admin (entre 1 - elle - et 3 personnes max). Ce serait possible qu'elle nous donne les adresses à rendre admin et qu'on les entre en dur quelque part... mais qui évidemment ne puisse pas être modifié (ni vu si possible) ?

> Qu'est-ce que tu penses de ce format bilans_climat_simplifies_2021-12-03.csv ?

Oui très bien.
Peut-être ajouter l'unité, ex:
_poste_1_tCO2e
poste_2_tCO2e
total_tCO2e_

Pour le séparateur des CSV, c'est toujours un problème en France de choisir je trouve ^^
Parfois c'est le `;` qui est choisi, quand il risque y avoir des virgules... mais là le seul risque est dans la raison sociale non ? quite à mettre des `""` autours de cette catégorie ?

**Comment by hfroot** [comment]
J'ai ajouté l'unité.

Oui, quand il y a une raison sociale avec des virgules, il y aura des `""` autour, le fichier en pj a un exemple de ça, est-ce que tu veux tester pour voir si ça marche ok avec tes logiciels ?

[bilans_climat_simplifies_2021-12-08(1).csv](https://github.com/datagir/bilansclimatsimplifies/files/7676943/bilans_climat_simplifies_2021-12-08.1.csv)

**Comment by hfroot** [comment]
@florianpanchout l'export privé est dispo pour les utilisateurs `isStaff === true` à `/api/v1/export`

**Comment by florianpanchout** [comment]
Téléchargement de l'export privé mis en place en front

**Comment by Clem-mrtn** [comment]
Encodage des accents

**Comment by Clem-mrtn** [comment]
Problème d'encodage du fichier excel => issue #22

**Comment by hfroot** [comment]
@florianpanchout en plus de la vérsion csv, j'ai ajouté un endpoint `/api/v1/xlsxExport` pour une option de téléchargement optimisé pour excel
à noté : je vais améliorer l'affichage de ce fichier, mais j'ai voulu pousser une première version rapidement

**Comment by florianpanchout** [comment]
Bouton ajouté sur la home

**Comment by hfroot** [comment]
@Clem-mrtn est-ce que tu peux valider le nouveau format pour celui-ci aussi ?

**Comment by Clem-mrtn** [comment]
Je suis pas admin je n'ai donc pas les droits pour télécharger ce fichier 😭 
@martinregner tu pourrais faire le test depuis la home ? 😬

**Comment by hfroot** [comment]
@Clem-mrtn je viens de mettre à jour les droits du compte avec l'adresse datagir :)

**Comment by Clem-mrtn** [comment]
J'ai le même message mais pareil impeccable à l'ouverture 😄 
![image](https://user-images.githubusercontent.com/76995768/149168101-9173fd7f-19d2-4e6f-af8d-a7074277d488.png)

C'est top !

**Comment by Clem-mrtn** [comment]
Par contre, juste question : quelle est la différence entre le lien et le bouton ?

![image](https://user-images.githubusercontent.com/76995768/149168219-c795b8dd-9c3c-4769-adae-e1e6f79c63e6.png)
 Y en a un qui me permet de télécharger en .csv / excel 
Et l'autre m'amène sur 
![image](https://user-images.githubusercontent.com/76995768/149168363-f950f85a-72b4-4b01-84f8-7ed5fbe2afea.png)

**Comment by hfroot** [comment]
Le lien est le jeu de données accessible au grand public - il y a pas encore des données qui on peut publier alors il n'y a rien à montrer sur cette page ademe open data pour l'instant.

**Comment by hfroot** [comment]
@florianpanchout xlsx/xls bug ici aussi je pense

**Comment by florianpanchout** [comment]
Corrigé
