### ISSUE TITLE
Ajouter un endpoint pour récuperer la liste des FE

### ISSUE THREAD

**Issue by florianpanchout** [datagir/bilansclimatsimplifies#16]
@hfroot Je ne peux pas accéder au json (https://github.com/datagir/bilansclimatsimplifies-backend/blob/main/data/static/emission-factors.json) en front (problème CORSà). C'est pour ça que je l'ai dupliqué dans l'app React pour l'instant

Est ce que tu peux ajouter un endpoint type `/emission-factors` qui me renverrait le contenu de ce json ?

**Comment by hfroot** [comment]
@florianpanchout est-ce que ça marche pour toi : https://bilansclimatsimplifies-staging.cleverapps.io/static/emission-factors.json ?

**Comment by florianpanchout** [comment]
Nope, problème de CORS

**Comment by hfroot** [comment]
Ah oui ? Je penserais qu'on peut accéder ça au même manier que les autres endpoints, après avoir obtenir un token avec /csrf... tu peux me donner l'erreur complete que tu vois ?

**Comment by florianpanchout** [comment]
Le classique : `No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Comment by hfroot** [comment]
Ok, j'ai créé un endpoint plus normale - est-ce que tu peux tester /api/v1/emissionFactors ? (dans deux mins)

**Comment by florianpanchout** [comment]
Ça fonctionne, merci !
