### ISSUE TITLE
Ajouter un bouton sauvegarder ?

### ISSUE THREAD

**Issue by florianpanchout** [datagir/bilansclimatsimplifies#17]
Est ce que l'on a vraiment besoin d'ajouter un bouton sauvegarder ? J'ai peur que ça crée de la confusion chez l'utilisateur et suis plus pour lui faire comprendre de manière plus explicite que son bilan est sauvegardé automatiquement. 

Dans ce sens j'ai ajouté un texte `Votre bilan est sauvegardé. Vous pouvez fermer cette page et revenir l'éditer plus tard` et ajouté des notifications à chaque édition. Qu'est ce que vous en pensez ?

**Comment by Clem-mrtn** [comment]
En fait, je me projetais : quand tu remplis un dossier sur un site publique par exemple, t'as souvent un bouton **"Enregistré comme brouillon".** C'est instinctif.
Du coup je me disais que ça pouvait être pas mal d'offrir cette option là aussi, mais peut-être que c'est superflu et qu'en fait il manquait juste ce petit texte informatif pour "informer/rassurer" l'utilisateur

**Comment by martinregner** [comment]
> J'ai peur que ça crée de la confusion chez l'utilisateur et suis plus pour lui faire comprendre de manière plus explicite que son bilan est sauvegardé automatiquement.

En effet.
Si c'est automatique c'est top !

**Comment by florianpanchout** [comment]
Ça marche, on laisse comme ça alors
