### ISSUE TITLE
Description des postes 1 et 2

### ISSUE THREAD

**Issue by florianpanchout** [datagir/bilansclimatsimplifies#18]
Quelle est la définition / présentation que l'on souhaite afficher pour chacun des postes (la ou j'ai mis le texte fixe : "La scope 1 concerne tous..." pour l'instant)

**Comment by Clem-mrtn** [comment]
Poste 1
> Texte introductif : 
Le poste 1 du Bilan Climat Simplifié correspond aux émissions directes de GES des sources fixes contrôlées par votre entreprise. Autrement dit, il s’agit des émissions liées à la combustion d’un combustible au sein de ces sources fixes que sont un brûleur, une turbine, une chaudière, un groupe électrogène, etc. 
Cette combustion peut servir à produire de la chaleur, un travail mécanique ou de l’électricité. Les combustibles concernés peuvent être d’origine fossile (produits pétroliers, houille, gaz, etc.) ou biogénique (biomasse, déchets organiques, etc.).
Pour faire le calcul, il faut vous munir des quantités de combustibles utilisées (en kWh ou en litre ou en kg ou …) par type de combustible (fioul, gaz naturel, plaquettes forestières, etc.). Ces données sont à collecter, pour l’année de reporting, au niveau des factures d’achat ou de livraison de combustibles, ou des compteurs d’énergie. Elles doivent être agrégées au périmètre de votre entreprise.

**Comment by Clem-mrtn** [comment]
Poste 2
> Texte introductif : 
Le poste 2 du Bilan Climat Simplifié correspond aux émissions directes de GES des sources mobiles contrôlées par votre entreprise. Autrement dit, il s’agit des émissions liées à la combustion de carburant au sein de ces sources mobiles, que sont les véhicules terrestres (voiture, tracteur, camion, chariots élévateurs, etc.), aériens (avion, jet, etc.), ferroviaires (train, métro), maritimes ou fluviaux. 
Le Poste 2 ne concerne que l’utilisation des sources mobiles contrôlées par l’entreprise, cela n’inclut pas les déplacements professionnels des salariés via des modes de transport non contrôlés par l’entreprise, ou les déplacements domicile-travail des salariés (hors véhicule de fonction), le déplacement des clients ou des visiteurs, etc. 
Pour faire le calcul, il faut vous munir des quantités de carburants consommées (en kWh ou en litre ou …) par type de carburant (essence, diesel, GNC, etc.). Ces données sont à collecter, pour l’année de reporting, au niveau des factures de carburant. Si les quantités consommées pour chaque carburant ne sont pas accessibles, il est possible d’extrapoler l’évaluation des émissions à partir du kilométrage parcouru et du tonnage transporté par type de véhicule. Les quantités doivent être agrégées au périmètre de votre entreprise.

**Comment by Clem-mrtn** [comment]
C'est les définitions qu'il y avait dans le specs de Fanny, du coup j'ai repris celles-ci

**Comment by florianpanchout** [comment]
Merci ! C'est ajouté
