### ISSUE TITLE
Créer l'URL - Homepage "Site en construction"

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/bilansclimatsimplifies#2]
L'URL du site sera communiquée dans le décret. 
Donc il faudrait MEL le site avec l'URL : https://www.bilans-climat-simplifies.ademe.fr
+ développer une HP d'attente (site en construction + laissez votre mail) 

**=> Deadline fin du mois Octobre**

**Comment by florianpanchout** [comment]
Quel serait le contenu de cette page ? A t'on un texte spéficique à afficher ? Ou irait l'adresse mail ?

**Comment by Clem-mrtn** [comment]
- Page avec design système de l'état 
- Reprendre un visuel type visuel ADEME (base impact)
-  **Wording** : 

_Bilans Climat Simplifiés
Sous-titre : Plateforme réglementaire pour le I. 1° de l’art. 244 de la loi n° 2020-1721 du 29 décembre 2020_

_Retrouvez très prochainement l'outil Bilan Climat simplifié afin de réaliser vos bilans carbone d'entreprise sur les postes 1 & 2 du scope 1. blabla un truc comme ça @martinregner ?_

- CTA Bouton Je veux être informé de sa sortie => laisser son email 
- Email qui créera une liste sur sendinblue pour faire un mailing de sortie de l'outils ?

**Comment by martinregner** [comment]
Proposition wording :

**_Bilans Climat Simplifiés_**
_Sous-titre : Plateforme réglementaire telle que prévue par l’article 244 de la loi n° 2020-1721 du 29 décembre 2020._

_Vous êtes une entreprise de moins de 500 salariés et avez reçu une aide de l’Etat dans le cadre du Plan de Relance ?
Vous pourrez prochainement calculer et publier votre Bilan Climat Simplifié sur ce site._

_Etre prévenu du lancement : `champ mail`_

> En savoir plus : 
> Le Bilan Climat Simplifié prévu au 1° du I de l'[article 244 de la loi n° 2020-1721](https://www.legifrance.gouv.fr/jorf/article_jo/JORFARTI000042753853) porte sur les émissions de Gaz à Effet de Serre (GES) directes produites par les sources d'énergie fixes et mobiles nécessaires aux activités de votre entreprise :
> - Le poste 1 du Bilan Climat Simplifié correspond aux émissions directes de GES des sources fixes contrôlées par votre entreprise ;
> - Le poste 2 du Bilan Climat Simplifié correspond aux émissions directes de GES des sources mobiles contrôlées par votre entreprise. 
> Le calculateur de ce site vous proposera - selon une approche de contrôle opérationnel - d’identifier et de quantifier ces émissions de façon cohérente avec la méthodologie réglementaire relative à l’article R. 229-49 du code de l’environnement._

**Comment by Clem-mrtn** [comment]
On pourrait rajouter une petite image pour habiller un peu ? 😃 
Très neutre le design système de l'état

**Comment by florianpanchout** [comment]
Pas convaincu par l'interêt d'une stock photo ici (mes arguments : https://www.nngroup.com/articles/photos-as-web-content/).

Sinon c'est bon pour le reste !

**Comment by Clem-mrtn** [comment]
Redirection => demande à Julien Labé

**Comment by florianpanchout** [comment]
Les contacts s'enregistrent dans https://my.sendinblue.com/users/list/id/75

**Comment by florianpanchout** [comment]
C'est en ligne : https://bilans-climat-simplifies.ademe.fr/
