### ISSUE TITLE
Gérer les deux types de bilans ("j'ai déjà fait..." / "je n'ai pas déjà fait...")

### ISSUE THREAD

**Issue by florianpanchout** [datagir/bilansclimatsimplifies#20]
Pour l'instant le choix de l'utilisateur est irrémédiable. Est ce qu'on laisse la possibilité sur la page bilan de changer de mode ? Et si oui, comment est ce que l'on présente ça ?

**Comment by Clem-mrtn** [comment]
Pas très bien compris : mais je propose qu'on se fasse une petite session lundi pour en discuter ?

**Comment by Clem-mrtn** [comment]
![image](https://user-images.githubusercontent.com/76995768/146782016-fe3a50d8-22f5-490f-9cf8-4149965b0dc6.png)

Très bien la phrase ! 
Je préciserai juste peut-être : 
>**"Vous pouvez fermer cette page et revenir éditer votre bilan plus tard depuis la rubrique "Mes Brouillons""** 

Un truc comme ça

**Comment by florianpanchout** [comment]
Done
