### ISSUE TITLE
Résultat undefined et localisation non prise en compte

### ISSUE THREAD

**Issue by florianpanchout** [datagir/bilansclimatsimplifies#21]
J'ai ajouté la possibilité de choisir la localisation du FE. Pour l'instant j'envoie un attribut `localisation`. L'api ne me renvoie pas d'erreur mais ne semble pas prendre en compte cet attribut (en tout cas elle ne me le retourne pas). 

Et l'attribut `resultat` est toujours vide.

@hfroot Qu'est ce que je fais mal ?

**Comment by hfroot** [comment]
Quel type d'émission et quelle localisation est-ce que tu as utilisé ?

**Comment by hfroot** [comment]
@florianpanchout déso - c'est un bug de mon côté. Je vais le régler maintenant

**Comment by hfroot** [comment]
@florianpanchout la localisation doit être prise en compte maintenant, est-ce que tu peux essayer encore ?

**Comment by florianpanchout** [comment]
Ça fonctionne maintenant. Merci !
