### ISSUE TITLE
Export CSV personnel

### ISSUE THREAD

**Issue by hfroot** [datagir/bilansclimatsimplifies#22]
Chaque utilisateur peut télécharger l'ensemble des données d'émissions pour chaque bilan. Cet export sera composé par une ligne par émission:

* type d'émission 
* valeur
* unité
* facteur d'émission
* résultat kgCO2e
* poste
* localisation
* note
* SIREN du bilan
* année du bilan

@martinregner tu peux valider ça ?

**Comment by hfroot** [comment]
Au lieu d'inclure des colonnes SIREN et année qui vont pas changé dans les lignes, on peut nommer le fichier `export_<SIREN>_<année>.csv` si tu préfères. (e.g. `export_012345678_2020.csv` ou `export_l_entreprise_vert_2020.csv`)

**Comment by hfroot** [comment]
@florianpanchout une première version du export est dispo `/emissionsExport/<bilan id>`

**Comment by florianpanchout** [comment]
Bouton ajouté sur la page récap du bilan

**Comment by martinregner** [comment]
1. Bug sur les valeurs qui ne sont pas dans les bonnes colonnes : vient de virgules qui sont dans les intitulés ?
2. Est-il possible de modifier le formatage du texte pour que les accents passent à l'ouverture dans Excel ?

![image](https://user-images.githubusercontent.com/46482115/147959426-b3d50605-00eb-41e5-a3a6-d4b36e8a1a06.png)

**Comment by Clem-mrtn** [comment]
- Encodage (accent)
- Problème de décalage de colonnes dans le fichier .csv (info pas dans les bonnes colonnes)

![image](https://user-images.githubusercontent.com/76995768/148048253-a14180bf-0fd0-4cd4-a8b0-eadda0ec700a.png)

**Comment by hfroot** [comment]
@martinregner  ou @Clem-mrtn est-ce que tu peux m'envoyer le fichier avec l'issu de décalage de colonnes ?

**Comment by martinregner** [comment]
Voilà le mien.
[bilan_2018_test.csv](https://github.com/datagir/bilansclimatsimplifies/files/7822002/bilan_2018_test.csv)

Le décalage vient a priori des 1 et 3 virgules dans les intitulés :
- GranulÃ©s bois, 8% d'humiditÃ©
- VUL, < 3,5 tonnes, GPL

**Comment by hfroot** [comment]
Merci, c'était utile. Je vois que le problème c'est pas avec le fichier csv mais avec excel - l'applis a des idées différentes que tout le monde sur les fichiers CSV... 
Pour ouvrir le fichier on doit:

1. Ouvrir un nouveau tableur dans excel
2. Clique File -> Import -> CSV File -> Import -> Choisi le fichier
3. Ensurer que 'Delimited' est choisi et 'File origin' est UTF-8
![Screenshot 2022-01-06 at 14 49 09](https://user-images.githubusercontent.com/9282816/148392699-618e82d9-6fa6-4cd4-9b50-d23a9d4df55d.png)
4. Choisi "comma" et text qualifier comme `"`
![Screenshot 2022-01-06 at 14 49 44](https://user-images.githubusercontent.com/9282816/148392807-519a448d-345d-47cd-a25f-21f1ec08fc7f.png)
5. Column data format "General"
![Screenshot 2022-01-06 at 14 50 36](https://user-images.githubusercontent.com/9282816/148392898-bf09e77f-3a42-45ab-a09b-e31b2791e05c.png)

On peut regarder ça par visio aussi, je sais que peut-être il y a des différences de langage ou applis (je suis sur un mac).

**Comment by martinregner** [comment]
Bizarre ... C'est bien comme ça que j'avais fait (je n'ai juste pas la partie File origin / UTF8).
Et comme ça prend toutes les virgules, celle au sein du type d'émission (ex. VUL, < 3,5 tonnes, GPL) sont aussi prises et décalent les colonnes d'après

**Comment by Clem-mrtn** [comment]
Et du coup est-ce que l'encodage en UTF8 ne peut pas "se programmer" pour que quand les gens ouvrent le .csv dans excel ils puissent lire correctement le fichier ?

**Comment by hfroot** [comment]
> Et du coup est-ce que l'encodage en UTF8 ne peut pas "se programmer" pour que quand les gens ouvrent le .csv dans excel ils puissent lire correctement le fichier ?

Je suis d'acc que ça sera mieux... je vais faire plus de recherche
@martinregner t'as toujours l'issue de décalage alors ?

**Comment by martinregner** [comment]
@Clem-mrtn en regardant avec @hfroot le problème vient d'Excel...
Je pense que c'est assez utilisé en entreprise.
Helen regarde si c'est pas trop compliqué de faire un export Excel (en plus de CSV).

Ca pourrait régler le problème d'UTF8 en même temps non ?

**Comment by hfroot** [comment]
@florianpanchout en plus de la vérsion csv, j'ai ajouté un endpoint `/api/v1/emissionsXlsxExport` pour une option de téléchargement optimisé pour excel
à noté : je vais améliorer l'affichage de ce fichier, mais j'ai voulu pousser une première version rapidement

**Comment by florianpanchout** [comment]
J'ai ajouté l'option sur la page bilan

**Comment by hfroot** [comment]
Merci, @Clem-mrtn est-ce que tu peux valider le nouveau format ?

**Comment by Clem-mrtn** [comment]
Ca fonctionne impeccable de mon côté pour l'export excel 
J'ai un message d'encodage à l'ouverture mais en vrai il s'ouvre correctement !
![image](https://user-images.githubusercontent.com/76995768/149166750-e1e30b26-4796-473c-8d30-8f5d456e1065.png)

![image](https://user-images.githubusercontent.com/76995768/149166805-3c92369d-743e-406b-913e-97e391f4cd0c.png)

(y a rien dans post 1 parce que j'ai pas rentré d'émission pour ce test)

**Comment by hfroot** [comment]
@florianpanchout je pense que l'extension que t'as donné le fichier n'est pas propre - c'est `xlsx` et pas `xls`

**Comment by florianpanchout** [comment]
Corrigé

**Comment by martinregner** [comment]
Ca marche, pas de message de mon côté !
