### ISSUE TITLE
Export PDF

### ISSUE THREAD

**Issue by hfroot** [datagir/bilansclimatsimplifies#23]

**Comment by hfroot** [comment]
@florianpanchout t'es d'accord que c'est plutôt côté front ?

**Comment by florianpanchout** [comment]
À voir ce qui est le plus simple à mettre en place mais probablement oui. Je regarderai

**Comment by florianpanchout** [comment]
@martinregner @Clem-mrtn Quelles sont les infos que l'on souhaite afficher dans ce pdf ? Est ce que c'est juste le résumé ou bien on veut le détail des émission de chaque poste ?

**Comment by martinregner** [comment]
Oui juste le résumé. Ce document est un accusé de publication.
Il reprend les informations principales :
-	Raison sociale de l’entreprise
-	SIREN
-	Année de reporting
-	Date de publication
-	Résultats Poste 1 / Poste 2 / Total du Bilan Climat Simplifié

**Comment by florianpanchout** [comment]
J'ai mis la possibilité d'imprimer la page (en la rendant un peu plus clean)

**Comment by Clem-mrtn** [comment]
- Spécifier davantage les boutons (Télécharger le bilan détaillé (.csv), Imprimer le récapitulatif du bilan)

**Comment by florianpanchout** [comment]
Done
