### ISSUE TITLE
Homepage (Fanny)

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/bilansclimatsimplifies#26]
- [x] Positionner le bouton **"M'inscrire ou me connecter"** en dessous du texte explicatif sur ce qu’est un BCS.
C’est moins user friendly, mais ça nous évitera aussi d’avoir 150 brouillons de bilans qui n’iront jamais plus loin car les gens se rendront compte que ce n’est pas ce qu’ils espéraient (on a beaucoup d’utilisateur qui cherche un outil open source pour faire son vrai Bilan GES).

- [x] Formulaire de contact : Insérer un **lien "Nous Contacter"** dans le footer qui redirige vers le formulaire tel quel 
Renvoyer les messages sur centrederessourcesges@ademe.fr avec en objet « Demande – Plateforme Bilans Climat Simplifiés ».

- [x]  Ajouter un bouton pour télécharger la base de données : je vous laisse voir où le positionner sur la page d’accueil

**Comment by florianpanchout** [comment]
Done

**Comment by Clem-mrtn** [comment]
C'est top ! 
Fanny va être très heureuse de ce petit contact 😆 

Pour le bouton "Télécharger" les exports est-ce qu'on le ferait pas plus en mode bouton qu'en lien ? Là ce n'est pas très visible ni très incitatif.
Mais c'est p-t le but ? on cherche p-t à moins le mettre en valeur ?

**Comment by Clem-mrtn** [comment]
Design système fait que ce n'est pas une bonne pratique de le mettre sous forme de bouton
=> option pour le mettre en valeur : le mettre dans un cadre grisé comme "Pour aller plus loin"

**Comment by florianpanchout** [comment]
Done
