### ISSUE TITLE
Formulaire inscription entreprise (Fanny)

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/bilansclimatsimplifies#27]
- [x] Reformuler/préciser les trois champs ci-contre
        - Section de nomenclature (code NAF, niveau I)
        - Région du siège de l’entreprise
        - Année de reporting du bilan
        - Sous-titre du champs « Année » : inférieure à 2022 => attention car l’obligation réglementaire n’a pas de date de fin et impose un BCS tous les 3 ans à partir de fin 2022, donc l’année de reporting ne sera pas toujours inférieure à 2022. **=> donc l'enlever** ?
        
**_Question_** : Quel contrôle est en place aujourd’hui sur l’année complétée ? @florianpanchout 
La règle côté Bilans GES, c’est que l’année de reporting doit être l’année n, n-1 ou n-2 par rapport à l’année de publication. On peut la reprendre ici et indiquer ça en sous-titre « année n, n-1 ou n-2 par rapport à l’année en cours » ?

- [x] Contrôler le nb max de salariés (jusqu'à 500 max). Dans les tests d’erreur, on a pu mettre 600 salariés.
- [x] Spécifier les messages d'erreur : il faudra bien préciser les erreurs à l’utilisateur car en l’état, c’est compliqué de savoir où elle se situe.

**_Question :_** : Pour la Région, quel est le numéro attendu ? Le numéro de la région ou le code INSEE de la région ? S’il s’agit du code INSEE, il faut a minima le préciser dans le sous-titre.
Est-il compliqué de mettre plutôt une liste déroulante avec les noms des différentes régions plutôt que de demander un numéro ?

**Comment by hfroot** [comment]
@florianpanchout est-ce que tu veux que j'ajoute des vérifications pour l'année et nombre salariés côté back aussi ?

**Comment by florianpanchout** [comment]
Yes, ça me semble pertinent d'avoir toutes les vérifications en back (en plus du front)

**Comment by hfroot** [comment]
Sur la page d’accueil, c'est écrit que l'outil est pour les entreprises entre 50 et 500 salariés - alors est-ce qu'on veut ajouter une vérification pour >=50 aussi que <=500 ?

**Comment by Clem-mrtn** [comment]
Carrément, oui je pense que c'est bien d'avoir les deux vérifications !

**Comment by Clem-mrtn** [comment]
J'ai un bug , j'ai pu créer un premier Bilan avec mon numéro de Siren.
Ensuite j'ai supprimé ce bilan pour pouvoir en réediter un nouveau avec le même numéro de siren et tester un nouveau parcours utilisateur et je suis coincée le formulaire me bloque avec un message d'erreur : 
![image](https://user-images.githubusercontent.com/76995768/146785451-6fe7808d-32c9-45e1-956f-e58287073da9.png)

**=> Je ne sais pas si c'est parce qu'il n'a pas encore enregistré qu'il n'y avait plus de bilan sous ce numéro ou alors il y a un autre bug.
PI j'ai tenté de laisser mon premier bilan existant, et d'en créer un nouveau en changeant uniquement le chiffre de fin pour le SIREN mais pareil j'était bloquée... (je me suis dis que ce Siren ne devait donc pas exister)**

**Comment by hfroot** [comment]
@Clem-mrtn je pense c'est au cause de l'année que tu utilises - il y a maintenant de la validation pour voir si l'année est n-2, n-1, ou n - 2018 c'est n-3.

**Comment by florianpanchout** [comment]
@hfroot Si j'essaie de créer un bilan avec un couple siren / année déja utilisé, l'api me renvoie une erreur 400 sans plus de détail. Possible de me préciser l'erreur ?

**Comment by hfroot** [comment]
@florianpanchout maintenant on retourne `'nonFieldErrors': ['Les champs siren, annee doivent former un ensemble unique.']` si il y a une duplication

**Comment by florianpanchout** [comment]
Possible de mettre un message plus grand public ? Du style `Un bilan avec ce couple SIREN / Année de reporting existe déjà.` (@martinregner @Clem-mrtn ou autre chose si vous avez plus compréhensible)

Comme ça je peux afficher directement la réponse de l'API sans passer par un dictionnaire d'équivalence en front

**Comment by hfroot** [comment]
J'ai mis à jour le message, ça sera prêt dans quelques minutes

**Comment by florianpanchout** [comment]
C'est en ligne
