### ISSUE TITLE
J'ai déjà fait mon bilan / Je n'ai pas déjà fait mon Bilan (Fanny)

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/bilansclimatsimplifies#28]
- [x] Reformuler ces deux encarts 
![image](https://user-images.githubusercontent.com/76995768/146202610-6cb64c0f-c36e-404c-b40d-fa47352a4d8d.png)
 Par : 
   - **ENCART 1 :** 
              **J'ai déjà calculé mon bilan simplifié** 
       Vous connaissez déjà le total de vos émissions des postes 1 et 2.
                                 _Bouton_ J’ai déjà calculé mon bilan
  - **ENCART 2 :**
              **Je souhaite calculer mon bilan simplifié**
        Vous avez besoin de calculer les émissions de toutes vos sources des postes 1 et 2 individuellement.
                                  _Bouton_  Je calcule mon bilan

- [x] Rajouter les accents à émissions 

           
![image](https://user-images.githubusercontent.com/76995768/146203160-b7475da1-81b2-44e3-a597-8fc8668c416b.png)

**Comment by florianpanchout** [comment]
Done
