### ISSUE TITLE
Bug formulaire "J'ai deja fait mon bilan" (fanny)

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/bilansclimatsimplifies#29]
Bug : cf. affichage ci-dessous => Pas d’affichage de la page permettant de publier mes informations. 

**Par contre,** une fois que je reviens vers mes bilans et que je retourne dessus, je peux éditer tout le contenu sans problème pour le modifier.

![image](https://user-images.githubusercontent.com/76995768/146204188-74fa6932-07a9-4a56-a9d9-1d730c2aeede.png)

**Comment by florianpanchout** [comment]
Ça devrait être corrigé
