### ISSUE TITLE
Formulaire Je calcule mon bilan : Les postes d'émissions 1 & 2 (Fanny)

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/bilansclimatsimplifies#31]
Post 1
- [x]  Reformuler  «  Type d’émission » par « Type de combustible »
- [x]  Reformuler « Valeur » par « Consommation (valeur) »
- [x] Reformuler  « Note » par « Commentaire »
- [x] Poste 1 - liste des FE :  inverser le gaz naturel proposé par défaut en haut de liste et le gaz naturel plus bas. 

**=> Est-il aussi possible de modifier la dénomination : garder « gaz naturel » pour le FE 2015 et mettre « gaz naturel, type H » et « gaz naturel, type B » plus bas dans la liste** ? @florianpanchout @hfroot 

![image](https://user-images.githubusercontent.com/76995768/146207675-9df197d8-23ee-43a3-8757-2a1369327b08.png)

- [ ] #35  Post 2- liste d'émissions : Rajouter un écran entre le au démarrage des Q. pour le post 2, où l'on aurait deux boutons 
      - BOUTON 1 :  **Je connais les consommations de carburant de mes véhicules**
      - BOUTON 2 : **Je connais les distances parcourues et tonnages transportés de mes véhicules**
   Au clique du Bouton 1, on aurait les wordings suivants : 
      - Remplacer « Type d’émission » par « Type de carburant » (choix 1) 
      - Remplacer « Valeur » par « Consommation (valeur) » 
      - « Note » par « Commentaire »
  Au clique du Bouton 2, on aurait : 
      - Remplacer « Type d’émission" par « Type de véhicule » (choix 2)
      - Remplacer « Valeur » par  « Distance et/ou t.km (valeur) » (choix 2)
      - « Note » par « Commentaire »

![image](https://user-images.githubusercontent.com/76995768/146207425-763dc84c-aadb-4eb6-a590-83fb39bfc521.png)

**Comment by florianpanchout** [comment]
@Clem-mrtn @martinregner la séparation carburant / véhicule implique de modifier la structure du fichier des FE. Ce n'est pas quelque chose qui prends 5 minutes (c'est du back donc @hfroot sera plus à même d'estimer le temps). Est ce qu'on souhaite vraiment le faire ?

**Comment by Clem-mrtn** [comment]
J'imagine un peu comme pour la question du dessus ?
> Est-il aussi possible de modifier la dénomination : garder « gaz naturel » pour le FE 2015 et mettre « gaz naturel, type H » et « gaz naturel, type B » plus bas dans la liste ? 

@hfroot combien de temps penses-tu que cela peut prendre de faire cette modification ?

**Comment by hfroot** [comment]
@Clem-mrtn Pour gaz naturel il y a [actuellement](https://github.com/datagir/bilansclimatsimplifies-backend/blob/fa686a525d6a91fc5ebc72460ed289f526633e99/data/static/emission-factors.json#L1136) deux 'localisations' : "France continentale : Type B, nord" et "France continentale : Type H, France continentale sauf nord". La solution le plus rapide c'est de modifier l'extrait des données pour déplacer le spécification de type B/H dès le champ de localisation à le champ de type où "attribute"/"frontière" comme les autres émissions. Mais ça introduit un différence, entre le BDD base carbone et l'extrait, et si jamais l'extrait est refait qqn devra rajouter cette modification. Est-ce que tu penses que ça posera un problème ?
Si on modifie les données dans l'extrait, ça va prendre une demi heure à refaire le fichier FE, et changer le groupe pour gaz naturel 2015 pour le mettre dans 'les plus utilisés' et les autres gaz naturels plus bas.

**Comment by florianpanchout** [comment]
On traite la séparation carburant / véhicule ici : https://github.com/datagir/bilansclimatsimplifies/issues/35

**Comment by hfroot** [comment]
@Clem-mrtn j'ai modifié deux lignes dans l'extrait pour mettre le `Type B, nord` et `Type H, France continentale sauf nord` dans l'attribut et pas la localisation, afin de rendre les deux types séperament dans la liste, et j'ai mis gaz naturel 2015 dans 'les plus utilisés' et les autres plus bas. Fait-moi signe si ça ne va pas.

**Comment by Clem-mrtn** [comment]
Ok super  😄  
Je me rends compte que l'on avait pas rebondi sur ton message ci-dessus concernant la différence entre la Base Carbone et du coup l'extrait des données.
En faisant ces modifications du coup on a bien une différence entre les deux et il faudra faire les mises à jour si besoin, manuellement c'est bien ça ?

**Comment by hfroot** [comment]
Oui, si on crée un nouveau extrait à l'avenir, on devra faire cette modif manuellement.
D'ailleurs, @martinregner m'a dit que Fanny a déjà fait quelques modifs manuellement avant elle nous a donné l'extrait.

**Comment by Clem-mrtn** [comment]
Ok bah parfait alors 😊
