### ISSUE TITLE
Ecran récapitulatif du bilan (fanny)

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/bilansclimatsimplifies#32]
- [x] Préciser Poste 1 – Emissions directes GES sources fixes
- [x] Préciser Post 2 – Emissions directes GES sources mobiles
- [x] Pour « Région » et « NAF », d’ajouter en plus du numéro, le nom de la Région et de la section de nomenclature 
- [x] Arrondir les totaux plutôt que de tronquer 
=> L’appliquer pour tous les champs valeur / total

- [x] Passer tous les résultats en **« tCO2e »** plutôt qu’en kgCO2e. **(partout où c'est chiffré)**

![image](https://user-images.githubusercontent.com/76995768/146210622-a171e8ed-ad68-4f6f-8bf7-7161c7e20abc.png)
![image](https://user-images.githubusercontent.com/76995768/146210639-f9d310d7-517e-47b8-b45b-67905d700775.png)

**Comment by hfroot** [comment]
@Clem-mrtn tous les FEs sont données comme "kgCO2e/<unité>" - est-ce que cette rêquete c'est pour une conversion en finale pour kg -> tonne ? 
Si oui, est-ce que tu peux confirmer que c'est 1kg = 0,001 tonne ?

**Comment by florianpanchout** [comment]
@hfroot Je m'occupe de cette issue en front. Ça me semble plus simple / pertinent de continuer nos échanges en kgCO2e, et que je m'occupe de l'affichage en tCO2Ee non ?

**Comment by hfroot** [comment]
@florianpanchout J'ai besoin quand même de calculer en tCO2e pour les exports. Je peux rendre ces calculs dispo dans le API `total_t`, `poste_x_t` si tu veux les utiliser (ou simplement changer les `total` et `poste_x` directement).

**Comment by florianpanchout** [comment]
Nope, pas besoin. Je fais déjà le calcul avec les kg (je doute que l'on ai une différence entre ton calcul et le mien ?)

**Comment by hfroot** [comment]
Petit retour - je pense ça peut être utile d'avoir un précision sur le champ pour les totals manuels que c'est max 3 chiffres significatifs. Maintenant si on mis plus, tout marche mais les derniers chiffres sont perdus.

**Comment by Clem-mrtn** [comment]
Pour les personnes qui ont déjà fait leur bilan et qui renseignent à la main les posts 1 & 2 ? Mettre une limite de 3 chiffre avant ou après la virgule ?

**Comment by Clem-mrtn** [comment]
Attention, je ne sais pas si on aura beaucoup de personnes dans ce cas, mais pour les petits résultats d'émissions, on se retrouve avec 0 tonne de CO2 affiché sur l'écran Bilan des Post 1 & 2 
=> cf. screen ci-dessous, j'étais à 145 kg de CO2 pour le post 2 et dans le récap là je suis à 0

![image](https://user-images.githubusercontent.com/76995768/146783711-76886eee-504b-47eb-b75d-9da699c2b5f0.png)

- Et + pour le coup j'aurais mis les informations de l'entreprise au dessus des résulats /poste 

=> Infos entreprise (tjrs en petit comme ça) 
=> Post 1 & Post 2 
=> Publier ce bilan 
qu'en pensez vous ?

**Comment by hfroot** [comment]
> Pour les personnes qui ont déjà fait leur bilan et qui renseignent à la main les posts 1 & 2 ? Mettre une limite de 3 chiffre avant ou après la virgule ?

Après le virgule - par ex "10,123" et jamais "10,1234". La validation côté back est déjà là - il coupe "10,1234" pour être "10,123".

À propos les petits chiffres - est-ce qu'on peut calculer/demander si c'est un cas probable ?

**Comment by florianpanchout** [comment]
J'ai enlevé l'arrondi pour les chiffres inférieurs à 1 tonne (on garde l'arrondi du back)

**Comment by florianpanchout** [comment]
Tout est traité normalement

**Comment by florianpanchout** [comment]
Ah non pas cette partie : 

> Et + pour le coup j'aurais mis les informations de l'entreprise au dessus des résulats /poste
=> Infos entreprise (tjrs en petit comme ça)
=> Post 1 & Post 2
=> Publier ce bilan
qu'en pensez vous ?

À noter que c'était comme ça avant et que je le change suite à cette issue (https://github.com/datagir/bilansclimatsimplifies/issues/12) que j'ai lu trop vite. Perso ça me semble logique d'afficher les totaux en premier. C'est ce que les gens veulent vérifier, le reste ils connaissent déjà.

**Comment by Clem-mrtn** [comment]
=> changer l'ordre 
ID 
Résultat Bilan

**Comment by florianpanchout** [comment]
Done
