### ISSUE TITLE
Section NAF ou Division NAF ? 

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/bilansclimatsimplifies#33]
- [x] Mettre en majuscule toutes les colonnes
- [x] Reformuler « Mode » par « Mode de publication » et de remplir avec les options "Déclaré » ou « Calculé »
- [x] Remplacer :
 - « gestionnaire » par « créateur du bilan »
 - « année » par « Année de reporting »
- « région » par « Code région »
- « naf » par « Code NAF »

**_Question :_** Est-il possible d’ajouter deux colonnes supplémentaires à côté de « région » et « naf » avec la dénomination en toute lettre de la région et de la section NAF ? =>** Les intituler : « Nom région » et « Section NAF »**

- [x] Pour l’export qui sera mis en open data, je propose de partir sur la même base mais de supprimer les colonnes : 
    - Mode de publication / 
    - Statut / 
    - Création_date / 
    - et toutes celles liées aux créateurs des bilans.

![image](https://user-images.githubusercontent.com/76995768/146210413-423951fa-2bfa-4481-987b-6f7ce5e7c890.png)

**Comment by hfroot** [comment]
Oui c'est possible d'avoir deux colonnes en plus avec nom région et texte NAF - mais pour clarifier j'ai utilisé la division NAF (88 options), et pas la section (21 options) car c'est ça que j'ai compris du trame, est-ce qu'on veut nommer le colonne "Division NAF" alors ?

**Comment by Clem-mrtn** [comment]
C'est quoi la différence entre Séction NAF & Division NAF ? Je ne maîtrise pas

**Comment by hfroot** [comment]
J'ai l'impression que les divisions sont plus précises que les sections. D'ailleurs j'ai trouvé la liste ici: https://www.insee.fr/fr/information/2120875

**Comment by Clem-mrtn** [comment]
Question à poser à Fanny @martinregner

**Comment by martinregner** [comment]
On garde les 88 divisions.

@florianpanchout je propose donc de changer `Section de nomenclature (code NAF, niveau I)`  en 
**`Secteur d'activité (NAF rév. 2)`**

**Comment by florianpanchout** [comment]
C'est fait pour le front.

(il restera l'export à modifier je crois)

**Comment by hfroot** [comment]
On veut quelle modification de l'export ? Maintenant les deux colonnes sont "Code NAF" (pour le chiffre de division) et "Division NAF" (pour le nom complet).

**Comment by martinregner** [comment]
En effet, pas utile donc de modifier l'export 👍
