### ISSUE TITLE
Page "Pour aller plus loin" 

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/bilansclimatsimplifies#34]
- [x] Rajouter un Encart « Pour aller plus loin » : je vous laisse voir où le positionner (un encart sur une page existante ou bien une page supplémentaire, etc.)

**Proposition de texte :**
Le Bilan Climat Simplifié est un bref aperçu du réel impact GES de votre entreprise et ses activités. En effet, pour la plupart des entreprises, 70% de vos émissions concernent des postes non calculés ici. Nous vous invitons donc à poursuivre l’exercice vers un Bilan GES exhaustif de vos émissions qui est le meilleur moyen de savoir où agir ! Rendez-vous sur notre Centre de Ressources dédié.

Au-delà de la quantification de vos émissions GES, l’ADEME vous accompagne dans la transition écologique de votre entreprise. Retrouvez toutes nos aides et offres d’accompagnement sur notre plateforme « AGIR pour la transition ».

**Comment by florianpanchout** [comment]
J'ai ajouté l'encart sur la page d'un bilan

**Comment by martinregner** [comment]
Je trouve ça très bien où il est positionné 👌 

Petites modifs :

- [x] Rendre `Centre de Ressources` cliquable, pour rediriger vers

https://www.bilans-ges.ademe.fr/fr/accueil/contenu/index/page/bilan%2Bges%2Borganisation/siGras/1
- [x] Modifier le deuxième § :
`L’ADEME vous accompagne plus globalement dans la transition écologique de votre entreprise. Retrouvez nos offres d’accompagnement et toutes nos aides sur AGIR pour la transition.`
- [x] Modifier l'URL AGIR pour : https://agirpourlatransition.ademe.fr/entreprises
- [x] Ajouter un espace entre les deux § :
![image](https://user-images.githubusercontent.com/46482115/146415266-68c0283c-aef7-4ab8-99cf-97ca960c1f73.png)


**_Piste évoquée avec AGIR_** : pourquoi pas un bouton (vert Agir ;) qui redirige vers la plateforme... A voir si cela peut rester lisible.

**Comment by florianpanchout** [comment]
Done, sauf le bouton Agir. Un bouton en tant que lien externe sort totalement des principes d'accessibilité du DSFR (je peux le faire, mais je ne le recommande pas, et ça me demandera de bidouiller le design system encore plus que maintenant)
