### ISSUE TITLE
Séparer les emissions du poste 2 (carburant / distance)

### ISSUE THREAD

**Issue by florianpanchout** [datagir/bilansclimatsimplifies#35]
Demande de Fanny : 

> Post 2- liste d'émissions : Rajouter un écran entre le au démarrage des Q. pour le post 2, où l'on aurait deux boutons
>- BOUTON 1 : Je connais les consommations de carburant de mes véhicules
>- BOUTON 2 : Je connais les distances parcourues et tonnages transportés de mes véhicules

Il faudrait donc pouvoir séparer les FE du poste 2 en deux (carburant / véhicule). @hfroot je propose d'ajouter un attribut `type` avec ces deux options (`carburant` / `véhicule`). Ça te va ?

**Comment by hfroot** [comment]
@florianpanchout c'est quoi le difference entre `"groupe": "Routier"` et `"groupe": "Non routier"` et les types que tu proposes ? (Est-ce que carburant = non routier et véhicule = routier ?)

**Comment by florianpanchout** [comment]
Nope c'est un autre attribut. Un carburant peut être `routier` ou `non routier`, et pareil pour véhicule.

**Comment by hfroot** [comment]
Ok, je vais l'ajouter. Est-ce qu'il y a une liste pour quel type d'émission a quel `carburant/véhicule` ? Je peux deviner entretemps

**Comment by florianpanchout** [comment]
@martinregner

**Comment by hfroot** [comment]
@martinregner peut-être tu peux vérifier directement si mes suppositions sont correctes : https://github.com/datagir/bilansclimatsimplifies-backend/commit/9c83395cd91092c6d4a2b2890a43b36a5107587c#diff-fefddaf889902093d4408b6410978756cc4fabc34158fd149563e6fbefb2f5bc 

@florianpanchout j'ai ajouté l'attribut `classification` car `type` est déjà utilisé pour le nom de type d'émission. Le changement est live.

**Comment by martinregner** [comment]
Merci @hfroot pour toutes les suppositions (très bonnes dans l'ensemble ;)
J'ai fait quelques commentaires d'endroits à modifier.

Cependant, la formule est différente que l'on transporte des personnes ou de la marchandise :
 
> -	Transport de personnes : kms parcourus x FE du mode de transport
> -	Transport de marchandise : tonne.km transportées x FE du mode de transport

Est-ce que la distinction `véhicule` est suffisante ? cela permet de demander l'unité associée `km` ou `t.km` ?

**Comment by hfroot** [comment]
Merci pour tes commentaires, je vais y travailler maintenant.

> Est-ce que la distinction véhicule est suffisante ? cela permet de demander l'unité associée km ou t.km ?

On utilise toujours les données dans l'extrait - il y a 124 FEs donnés pour l'unité `kgCO2e/t.km` ([exemple](https://github.com/datagir/bilansclimatsimplifies-backend/blob/d7984266c93e2d592c5363553fbb6fe221ea5066/data/static/emission-factors.json#L35)) et 41 pour `kgCO2e/km` ([exemple](https://github.com/datagir/bilansclimatsimplifies-backend/blob/d7984266c93e2d592c5363553fbb6fe221ea5066/data/static/emission-factors.json#L976)). Ça suffit d'utiliser ces valeurs ?

**Comment by martinregner** [comment]
Oui très bien !

**Comment by hfroot** [comment]
J'ai finit les commentaires t'as laissé sur carburant/véhicule et routier/non routier

**Comment by florianpanchout** [comment]
On demande maintenant à chaque ajout d'une émission pour le poste 2 si on souhaite ajouter un carburant ou un véhicule. L'info n'est pas renvoyée au back

**Comment by Clem-mrtn** [comment]
Top, ça fonctionne très bien ! 

**Juste petite remarque** : Lorsque je clique sur l'un des deux boutons, j'arrive sur le formulaire du post 2.
MAIS si je fais précédent (imaginons parce que je me suis trompée) je ne retombe pas sur l'écran avec choix carburant / choix véhicules mais sur l'écran encore d'avant.
=>Ex : je faisais le test depuis mes Brouillons, en faisant précédent de la page formulaire je revenais à la page recap du Bilan.
Il fallait que je reclique sur Edit Post 2 > Ajouter une émission > pour que je retombe sur l'écran choix 1 / choix 2 

On pourrait retourner à l'écran Choix Véhicule / Choix carburant ?

**Comment by florianpanchout** [comment]
Je peux mettre une option pour modifier son choix, mais prendre en compte la navigation navigateur pour ça m'oblige à modifier toute la structure

**Comment by florianpanchout** [comment]
@hfroot J'ai besoin que https://bilansclimatsimplifies-staging.cleverapps.io/api/v1/bilans/{id}/emissions me renvoie la classification de chaque émission (pour ne pas re-proposer le choix à chaque édition)

**Comment by hfroot** [comment]
@florianpanchout c'est ajouté

**Comment by florianpanchout** [comment]
Parfait, merci.

C'est bon, on laisse maintenant la possibilité à l'utilisateur de modifier son choix

**Comment by martinregner** [comment]
C'est parfait comme ça ! 👍
