### ISSUE TITLE
Émissions dans les deux postes

### ISSUE THREAD

**Issue by hfroot** [datagir/bilansclimatsimplifies#36]
Biodiesel et Bioéthanol peuvent être si dans poste 1 ou 2, alors on doit les afficher dans les deux listes déroulantes. (discuté ici: https://github.com/datagir/bilansclimatsimplifies/issues/6#issuecomment-992276344)

@florianpanchout comment est-ce que tu veux recevoir l'information sur poste et groupe pour ces émissions ? Deux idées :

1.
Dans emission-factors.json :
```
"poste": "1+2", ou ["1", "2"]
"groupe": "+routier", ["", "routier"]
```
2. Gérer ces émissions côté front complètement un peu hardcoded

Car on envoie "poste" avec l'émission et il n'y a pas de validation sur combinaison poste+type d'émission, le problème c'est seulement dans l'affichage des options quand l'utilisateur enregistre une émission.

**Comment by florianpanchout** [comment]
Le plus viable me semblerait de fonctionner avec un array : `"poste": ["1", "2"]`

**Comment by hfroot** [comment]
C'est live
