### ISSUE TITLE
Création de compte 

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/bilansclimatsimplifies#37]
Cette page permet la création d’un compte utilisateur.
Le formulaire d’inscription demande (à voir selon les besoins des comptes ADEME) :
o	Nom
o	Prénom  
o	Mail
o	Raison sociale de l’entreprise    
o	Mot de passe
o	Une case à cocher sur les règles RGPD et le fait que leurs données personnelles seront transmises aux autorités administratives pour le besoin du suivi de l’obligation réglementaire en question

**Comment by hfroot** [comment]
La raison sociale de l'entreprise c'est plutôt pour la page création de bilan non ? Parce que un utilisateur peut créer des bilans pour plusieurs entreprises.

**Comment by florianpanchout** [comment]
Territoires en Transitions n'a que Email, Nom, Prénom et RGPD (https://app.territoiresentransitions.fr/auth/register/). J'imagine que l'on peut faire comme eux.

@hfroot Est ce que tu as parlé de la création de compte avec Samuel ? On peut juste appeler un endpoint chez eux avec le formData (sans passer par notre backend), ou c'est plus complexe que ça ?

**Comment by hfroot** [comment]
@florianpanchout je viens de finir la discussion avec Samuel, je pense que le front devra faire un appel vers le back avec les données dans le formulaire, et le back va gérer l'appel vers keycloak (il y a quelques secrets qui ne peuvent pas être exposé au front, en plus on doit configurer le serveur pour faciliter la connexion avec keycloak).

**Comment by Clem-mrtn** [comment]
> La raison sociale de l'entreprise c'est plutôt pour la page création de bilan non ? Parce que un utilisateur peut créer des bilans pour plusieurs entreprises.

Effectivement 
Après c'était dans le cahier des charges de Fanny ! Mais de ce que j'ai compris ce matin de toute façon ils vont s'inscrire via Agir ?

**Comment by hfroot** [comment]
> Effectivement Après c'était dans le cahier des charges de Fanny ! 

Ce que j'ai compris c'est que après le cahier a été écrit, on a identifié qu'un utilisateur peut gérer plusieurs entreprises, alors ça donne plus de sens de saisir cette info avec la création du bilan ?

> Mais de ce que j'ai compris ce matin de toute façon ils vont s'inscrire via Agir ?

C'est un mesure temporaire qu'on va tenter pendant qu'on construit l’intégration sur notre propre site, mais je dois au premier temps demander à l'équipe si ça va avoir des effets secondaires pour eux (par exemple, polluer leur BDD avec nos utilisateurs). @martinregner va me trouver un contact dans cette équipe pour que je puisse poser la question.

**Comment by Clem-mrtn** [comment]
> Ce que j'ai compris c'est que après le cahier a été écrit, on a identifié qu'un utilisateur peut gérer plusieurs entreprises, alors ça donne plus de sens de saisir cette info avec la création du bilan ?

C'est tout à fait vrai ! Très bien faisons comme ça !

Ok très clair !

**Comment by hfroot** [comment]
Des nouvelles :
Je peux créer un compte en locale ! Mais il y a qqs autres choses a régler :
- L'hébergeur, CleverCloud, n'a pas beaucoup de documentation de comment on connecte avec un VPN (c'est nécessaire pour la création de compte) alors je dois attendre des réponses de leur customer service de temps en temps. Leur temps de réponse est assez court mais je découvre des nouvelles questions avec chaque étape. J'ai contacté Maël ce soir pour voir si ça sera mieux d'utiliser scalingo (ou ces fonctionnalités sont mieux développées).
- Il me semble qu'il y a des problèmes avec les serveurs de pre-prod chez ademe connect - je reçois pas à télécharger les pages de connexion. J'ai envoyé un mail à Samuel.

Malgré ça, si tu veux tu peux commencer construire la page d'inscription @florianpanchout. L'API va être `/api/v1/ademeAccount` et il attend `Content-Type: multipart/form-data` avec `email`, `firstname`, `lastname`, et `"cgu": "true"`. Si t'as des retours n'hésites pas de les suggérer. 

Sur les CGU, territoires en transitions a un lien vers https://www.ademe.fr/lademe/infos-pratiques/politique-protection-donnees-a-caractere-personnel - je pense que c'est ça que l'utilisateur doit accepter

**Comment by martinregner** [comment]
Pour les CGU, je propose plutôt celles d'Agir qui apparaissent à la [création de compte](https://agirpourlatransition.ademe.fr/user/register), où ils distinguent CGU et protection des données : 
https://agirpourlatransition.ademe.fr/conditions-generales-dutilisation
https://agirpourlatransition.ademe.fr/politique-protection-donnees-a-caractere-personnel
![image](https://user-images.githubusercontent.com/46482115/148816472-f0b8b46d-d58a-45f7-ae30-d10aa990b393.png)

Pour nous c'est la **politique de protection des données** qui est pertinente.

**Comment by florianpanchout** [comment]
@martinregner Donc je ne mets qu'une checkbox `J'accepte la politique de protection des données personnelles de l'ADEME` avec un lien vers https://agirpourlatransition.ademe.fr/politique-protection-donnees-a-caractere-personnel ?

**Comment by Clem-mrtn** [comment]
Créer des comptes par Samuel pour que les ministères puissent faire le test 
=> normalement envoyer une version "presque finalisée" @Fanny **fin de semaine** pour qu'elle donne le GO à la DGEC

**Comment by florianpanchout** [comment]
Formulaire de login fait en front : https://staging--bilansclimatsimplifies.netlify.app/inscription

**Comment by Clem-mrtn** [comment]
Du coup pour l'instant on fait pas de contrôles ? 
Sur la validation des CGU, ou le format du mail par exemple

**Comment by florianpanchout** [comment]
Effectivement, l'input du mail était type="text" donc le navigateur ne faisait pas de vérification. C'est corrigé.

Pour la validation des CGU, tu ne peux pas valider le formulaire sans les avoir accepter non ?

**Comment by Clem-mrtn** [comment]
> Pour la validation des CGU, tu ne peux pas valider le formulaire sans les avoir accepter non ?

Dans tous les cas vu que ça ne fonctionne pas lorsque je clique sur valider, rien ne se passe. 
Mais le bouton reste cliquable et surligné bleu, que j'accepte ou non les CGU 
![image](https://user-images.githubusercontent.com/76995768/148962671-abbb3de2-edeb-43d2-ad6a-203f2099c89e.png)

**Comment by hfroot** [comment]
@florianpanchout est-ce que tu peux tester chez toi si tu peux créer un compte quand tu utilises le back `bilansclimatsimplifies.osc-fr1.scalingo.io`, plutôt que clevercloud ?

**Comment by hfroot** [comment]
Ah ignorer moi pour l'instant - je peux le tester au premier chez moi

**Comment by hfroot** [comment]
Mes tests ont réussites cet aprèm, on peut en discuter plus demain, je veux pas déranger les tests si ils ont été commencés en changeant les variables d'environnement.

**Comment by hfroot** [comment]
@florianpanchout est-ce que tu peux compléter la fonction `onSuccess` ? Dans ce cas, l'utilisateur récoit un mail d'ADEME pour créer un mdp.
Les deux erreurs prévues (400) donne un message dans le réponse :
"Données manquantes : on attend email, firstname, lastname, et cgu"
"Un compte existe déjà avec cet email."
Mais maintenant c'est en format HTML - j'imagine tu veux l'avoir en JSON ?

**Comment by Clem-mrtn** [comment]
+ Peut-être ajouter un message de confirmation ou un écran intermédiaire qui invite à consulter ses mails pour valider son compte définitivement ?

**Comment by florianpanchout** [comment]
@hfroot Ah oui je préférerais du json si c'est possible :)

**Comment by hfroot** [comment]
@florianpanchout c'est fait - `body.message` contiendra le détail comme décrit au-dessus.

**Comment by florianpanchout** [comment]
Parfait merci !

C'est en place (je considère toute `200` comme une création de compte valide), avec un message invitant à regarder ses mails
