### ISSUE TITLE
Bilan non trouvé

### ISSUE THREAD

**Issue by florianpanchout** [datagir/bilansclimatsimplifies#38]
À la création d'un bilan, je reçois son id en réponse de la requete POST. Lorsque j'essaie de communiquer avec cet id (par exemple https://bilansclimatsimplifies-staging.cleverapps.io/api/v1/bilans/64 en GET), je reçois : 

```
{"detail":"Pas trouvé."}
```

**Comment by hfroot** [comment]
T'es connecté en tant que quel utilisateur ?

**Comment by florianpanchout** [comment]
`florian.panchout@beta.gouv.fr`

**Comment by hfroot** [comment]
Hmm, c'est étrange. Depuis le 6 janvier, aucun nouveau bilan à un créateur liée avec. Je continue d'investiguer

**Comment by florianpanchout** [comment]
Le problème n'a pas l'air d'être lié à mon compte, @Clem-mrtn a le même

**Comment by hfroot** [comment]
J'ai trouvé le problème - un gaffe de ma part. Ça doit être résolu, tu peux créer des bilans à nouveau.
