### ISSUE TITLE
Retours ministère

### ISSUE THREAD

**Issue by martinregner** [datagir/bilansclimatsimplifies#39]
### Année de reporting :

- [x] Si l'on renseigne une année inférieure à l'année n-2 le message d’erreur suivant s'affiche : « Votre formulaire comporte des erreurs. Le champ Année de reporting du bilan n'est pas correctement rempli. ». Peut-être pourrait-il être plus explicite avec un message du type "L'année de reporting renseignée ne peut pas être inférieure à ...". 

### Effectif salarié :

- [x] Lorsque l’on renseigne un effectif salarié supérieur à 500 ou inférieur à 50, le message d’erreur suivant s’affiche : « Votre formulaire comporte des erreurs. Le champ Nombre de salariés n'est pas correctement rempli. ». Ce message n’indique pas clairement que l'erreur est que la valeur se situe en-dehors de l'intervalle [50;500]. Enfin, il s’affiche lorsque l’on a renseigné toutes les cases et cliqué sur « Commencer mon bilan », et non lors de la saisie.

### Calcul des émissions :

- [x] _Valider la complexité / faisabilité / pertinence UX_ Lorsque le combustible et l’unité sont choisis, le détail du facteur d’émission n’apparaît pas. Il pourrait être intéressant de l'afficher directement sur la plate-forme pour plus de transparence, bien qu'il apparaisse effectivement dans le bilan détaillé éditable après publication.

- [x] 	Le total affiché des émissions calculées est arrondi à l’unité, ce qui entraîne l'affichage d'un total nul si les émissions sont inférieures à 0,5 kgCO2e.

- [x]  La liste des intitulés de FE est à harmoniser (met en avant les erreurs d'harmonisation de la BC). C’est trompeur pour des utilisateurs non aguerris. Envoyer la liste des FE avec les quelques paramètres clés utilisés dans l’appli à Fanny qui se charge de revoir les dénominations pour que ce soit harmonisé.

**Comment by Clem-mrtn** [comment]
+1 pour le select de l'année de reporting

**Comment by florianpanchout** [comment]
C'est fait sauf 

> Valider la complexité / faisabilité / pertinence UX Lorsque le combustible et l’unité sont choisis, le détail du facteur d’émission n’apparaît pas. Il pourrait être intéressant de l'afficher directement sur la plate-forme pour plus de transparence, bien qu'il apparaisse effectivement dans le bilan détaillé éditable après publication.

Je n'ai aucune idée de si c'est pertinent ou non de l'afficher. J'ai l'impression que ce serait ajouter une information complémentaire pas forcement utile pour l'utilisateur

**Comment by hfroot** [comment]
>  La liste des intitulés de FE est à harmoniser (met en avant les erreurs d'harmonisation de la BC). C’est trompeur pour des utilisateurs non aguerris. Envoyer la liste des FE avec les quelques paramètres clés utilisés dans l’appli à Fanny qui se charge de revoir les dénominations pour que ce soit harmonisé.

Est-ce que ça suffit d'envoyer le fichier de FE, ou est-ce que vous avez besoin de qqch autre ?
https://github.com/datagir/bilansclimatsimplifies-backend/blob/main/data/static/emission-factors.json

**Comment by martinregner** [comment]
Merci @hfroot ; je vais lui envoyer ça comme ça tu as raison, plus facile à intégrer ensuite.

**Comment by Clem-mrtn** [comment]
> La liste des intitulés de FE est à harmoniser (met en avant les erreurs d'harmonisation de la BC). C’est trompeur pour des utilisateurs non aguerris. Envoyer la liste des FE avec les quelques paramètres clés utilisés dans l’appli à Fanny qui se charge de revoir les dénominations pour que ce soit harmonisé.

@hfroot Fanny va directement le faire d'elle-même sur le Github ! 
Au cas où est-ce que tu pourras vérifier, on est pas sûre que tu sois notifiée lorsqu'elle aura fait les modifs ? 
Merci bcp :)

**Comment by hfroot** [comment]
@Clem-mrtn nickel :) oui je pense que je recevrai une notif et aurai l'opportunité de vérifier les changements avant qu'ils sont intégrés dans la branche main.

**Comment by martinregner** [comment]
Normalement c'est bon @hfroot :)
Voici le retour et complément de la part de Fanny :

_Je l’ai fait en deux fois… donc vous devez avoir deux fichiers de propositions (environ 250 premières lignes puis le reste). Par contre, je n’ai pas l’impression d’y avoir accès une fois que je vous les ai envoyé. Donc n’hésites pas à me dire si ça n’a pas fonctionné._

_Je n’ai touché qu’aux intitulés des FE. Je n’ai pas osé toucher plus mais il faudrait :_
- [ ] _Supprimer les FE ligne 614 / 631 / 1493 (les deux premiers ne sont pas utiles car déjà couverts par d’autres FE, le dernier me semble superflu au vu des acteurs que l’on touche, surtout que ce ne sera pas pris en compte dans du scope 1)_
- [ ] _Modifier la catégorie des FE ligne 1325 & 1336 : ce sont des véhicules et non des carburants_
- [ ] _Modifier les valeurs des FE ligne 2618 & 3190 pour les mettre à 0 : en scope 1, on ne compte pas la fabrication des véhicules, uniquement la combustion du carburant (ici on est sur des véhicules élec, donc c’est 0)._

**Comment by hfroot** [comment]
@martinregner hmm, je vois pas les changements qu'elle a fait. Est-ce qu'elle peut nous envoyer le lien vers ces changements ?

**Comment by hfroot** [comment]
Une petite question pour Fanny : le texte proposé pour le FE identifié par `Articulé, 34 à 40 tonnes, Diesel routier, incorporation 7 % de biodiesel`, ligne 31, a été donné deux affichages différents dans ses changements :
[Articulé, 34 à 40 tonnes, Diesel routier 7 % de biodiesel](https://github.com/datagir/bilansclimatsimplifies-backend/pull/50/files)
[Articulé, 34 à 40 tonnes, Diesel avec incorporation 7 % de biodiesel](https://github.com/FannyFleuriot/bilansclimatsimplifies-backend/commit/5480070f68d31a958e4a8c975913c2b389678925)
C'est quoi le texte voulu ?
@martinregner est-ce que tu peux renvoyer cette question ?

**Comment by martinregner** [comment]
Merci @hfroot pour le check de ce qu'elle a rentré !
Elle vient de me répondre que l'enjeu est que ce soit cohérent sur la base (sans être sûr qu'elle avait pris la même logique tout le long).

Je vois : 
- ligne 30-31 : 
```
"Articulé, 34 à 40 tonnes, Diesel routier, incorporation 7 % de biodiesel": {
    "affichage": "Articulé, 34 à 40 tonnes, Diesel avec incorporation 7 % de biodiesel",
```
- L74-75 : 
```
"Articulé, 40 à 44 tonnes, Diesel routier, incorporation 7 % de biodiesel": {
    "affichage": "Articulé, 40 à 44 tonnes",
```
- L85-86 : 
```
"Articulé, 44 à 60 tonnes, Diesel routier, incorporation 7 % de biodiesel": {
    "affichage": "Articulé, 44 à 60 tonnes",
```
- L96-97  : 
```"Articulé, 60 à 72 tonnes, Diesel routier, incorporation 7 % de biodiesel": {
    "affichage": "Articulé, 60 à 72 tonnes",
```
- L118-119 : 
```
"Articulé, < 34 tonnes, Diesel routier, incorporation 7 % de biodiesel": {
    "affichage": "Articulé, < 34 tonnes",
```
- L 2251 - 2252 : 
```
"Rigide, 12 à 20 tonnes, Diesel routier, incorporation 7 % de biodiesel": {
    "affichage": "Rigide, 12 à 20 tonnes, Diesel routier (B7)",
```
- L 2284-2285 : 
```
"Rigide, 20 à 26 tonnes, Diesel routier, incorporation 7 % de biodiesel": {
    "affichage": "Rigide, 20 à 26 tonnes, Diesel routier (B7)",
```
- L2317-2318 : 
```
"Rigide, 26 à 32 tonnes, Diesel routier, incorporation 7 % de biodiesel": {
    "affichage": "Rigide, 26 à 32 tonnes",
```
- L2328-2329 : 
```
"Rigide, 3,5 à 7,5 tonnes, Diesel routier, incorporation 7 % de biodiesel": {
    "affichage": "Rigide, 3,5 à 7,5 tonnes, Diesel routier (B7)",
```
- L 2383-2384 : 
```
"Rigide, 7,5 à 12 tonnes, Diesel routier, incorporation 7 % de biodiesel": {
    "affichage": "Rigide, 7,5 à 12 tonnes, Diesel routier (B7)",
```
- L 2673-2674 :
```
"VUL, < 3,5 tonnes, Diesel routier, incorporation 7 % de biodiesel": {
    "affichage": "VUL, < 3,5 tonnes, Diesel routier (B7)",
```


Je propose de mettre partout `Diesel routier (B7)`
J'ai fait une [PR](https://github.com/datagir/bilansclimatsimplifies-backend/pull/54) avec cette proposition. C'est bon pour toi ?

**Comment by hfroot** [comment]
Merci @martinregner, j'ai mergé ta PR

**Comment by hfroot** [comment]
@martinregner J'ai fait les changements restants de [ce commentaire](https://github.com/datagir/bilansclimatsimplifies/issues/39#issuecomment-1036292908), si Fanny voudrait les vérifier :

https://github.com/datagir/bilansclimatsimplifies-backend/commit/cc23cab3f9f2edd071a40340235457f8e1f1a4d8

**Comment by martinregner** [comment]
Top, merci @hfroot !
Je lui dis que tout est modifié.
