### ISSUE TITLE
Modifs de forme sur landing

### ISSUE THREAD

**Issue by martinregner** [datagir/bilansclimatsimplifies#4]
"Top ! C’est nickel." dixit Fanny.

Deux petites remarques à la marge :
-	Est-il possible de rajouter un lien vers Legifrance sur l’article de loi ? -> 
https://www.legifrance.gouv.fr/jorf/article_jo/JORFARTI000042753853
-	Rajouter un espace entre le dernier bullet point et la dernière phrase pour que ce soit plus joli :)

![image](https://user-images.githubusercontent.com/46482115/137490648-3734ddda-e04d-4d2d-8694-0f2b35291491.png)

**Comment by florianpanchout** [comment]
"C’est nickel." ahaha mais c'est même pas fini

**Comment by florianpanchout** [comment]
C'est fait !
