### ISSUE TITLE
Détailler les calculs avec les FE (retours ministère) 

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/bilansclimatsimplifies#40]
Valider la complexité / faisabilité / pertinence UX Lorsque le combustible et l’unité sont choisis, le détail du facteur d’émission n’apparaît pas. Il pourrait être intéressant de l'afficher directement sur la plate-forme pour plus de transparence, bien qu'il apparaisse effectivement dans le bilan détaillé éditable après publication.

**Comment by martinregner** [comment]
Retour de Fanny qui pense aussi que c'est intéressant à développer dès la première version si possible :

> Concernant l’affichage de la valeur du FE, c’est vrai que cela va alourdir un peu, mais en même temps ça peut avoir un vrai intérêt pédagogique pour les utilisateurs. Autant cela est lourd et avec très peu d’intérêt pour des interfaces avec « tout le bilan carbone », autant notre contexte est un peu différent dans le sens où cette obligation est avant tout pour sensibiliser à l’exercice et « éduquer » les entreprises. Du coup, afficher la valeur du FE pourrait permettre aux utilisateurs de voir la valeur carbone des différentes énergies.

**Comment by florianpanchout** [comment]
Done
