### ISSUE TITLE
Certificat d'accessibilité 

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/bilansclimatsimplifies#44]
[2022-05-12_bilans-climat-simplifies_declaration-accessibilite-RGAA4-1.docx](https://github.com/datagir/bilansclimatsimplifies/files/8799598/2022-05-12_bilans-climat-simplifies_declaration-accessibilite-RGAA4-1.docx)

**Comment by florianpanchout** [comment]
" L’ADEME invite les personnes qui rencontreraient des difficultés à la contacter [xxx] afin qu’une assistance puisse être apportée (alternative accessible, information et contenu donnés sous une autre forme)."

Je remplace le [xxx] par quoi ?

**Comment by Clem-mrtn** [comment]
Je mettrai soit le mail datagir@ademe.fr soit alors je regardais sur le site d'Agir ils ont un mail contact référent accessibilité : rgaa@ademe.fr 

Est-ce qu'on pourrait l'utiliser @martinregner ? Y a une consigne là dessus côté Ademe ?

**Comment by florianpanchout** [comment]
J'ai mis [rgaa@ademe.fr](mailto:rgaa@ademe.fr) pour l'instant
