### ISSUE TITLE
Limite à 50 salariés

### ISSUE THREAD

**Issue by broussea1901** [datagir/bilansclimatsimplifies#45]
Pourquoi fixer une limite basse sur le nombre de salariés pour ce bilan ?
96% des 3,8 millions d'entreprises ont moins de 10 salariés.
Sans doute moins de 1% des entreprises sont dans le critère 50 < x < 500.

**Comment by hfroot** [comment]
Merci pour votre question - la limite basse est fixé par la loi. Vous pouvez lire plus ici : https://www.economie.gouv.fr/files/files/directions_services/plan-de-relance/FAQ_Entreprises_France_Relance.pdf?v=1643372205
