### ISSUE TITLE
Contrat d'interface front/back

### ISSUE THREAD

**Issue by florianpanchout** [datagir/bilansclimatsimplifies#5]
Voici une première proposition pour les différents endpoints accessibles en front. 

Pour la liste des sources d'émissions, je me dis qu'il sera peut être intéressant de les calculer via une fonction lambda séparée du back. Ça permettrais d'avoir la liste de tous les facteurs, de leurs unités et des facteurs d'émissions associés dans un fichier json ou markdown, plus simple à éditer pour des personnes non dev. 

(Je n'ai pas mis les fonctions d'export pour l'instant)

Dis moi ce que tu en penses :) 

# user
```
{
	"id": int,
	"nom": string,
	"email": string,
	... // selon ce que retourne l'auth ADEME
}
```
#### /user
`POST` pour créer un utilisateur (l'id est fourni par le systeme d'auth et pas généré automatiquement)

---
# bilans
### Format
```
{
	"id": int,
	"user": int,
	"siren": int,
	"raison_sociale": string,
	"naf": string,
	"nombre_salaries": int,
	"region": string,
	"annee": int,
	"poste_1": number, // S'incrémente automatiquement à chaque nouvelle source d'émission 
	"poste_2": number, // S'incrémente automatiquement à chaque nouvelle source d'émission 
	"total": number // Calculé à la validation du bilan
}
```
#### /bilans
`GET` pour récupérer tous les bilans d'un utilisateur
#### /bilans/{id}
`GET` pour récupérer un bilan
#### /bilans/{id}/emissions
`GET` pour récupérer toutes les sources d'émission d'un bilan
#### /bilans
`POST` pour créer un bilan
#### /bilans/{id}
`POST` pour éditer un bilan

--- 
# emissions
```
{
	"id": int,
	"bilan": int,
        "poste": int,
	"type": string,
	"valeur": number,
	"unite": string,
	"resultat": string
}
```
#### /emissions/{id}
`GET` pour récupérer une source d'émission
#### /emissions
`POST` pour créer une source d'émission
#### /emissions/{id}
`POST` pour éditer une source d'émission
#### /emissions/{id}
`DELETE` pour supprimer une source d'émission

**Comment by hfroot** [comment]
Quelques suggestions/questions:

Est-ce que tu veux récevoir les clés en format camelCase plutôt que snake_case ? C'est simple à faire à mon coté si oui.

Si il existe déjà un bilan avec l'année et SIREN donnés, est-ce que ça te va de récevoir un 400 ?

Je pense qu'on n'a pas besoin de inclure l'`user` dans les données du bilan, parce que le plupart d'utilisateurs verront seulement leur bilans.

un GET /bilans pour page 4/9 dans le wireframe

> /emissions/{id}/emissions

-> /bilans/{id}/emissions

Est-ce qu'on a besoin des DELETEs pour le bilan et/ou emissions ?

> /bilans/{id}/emissions

Ça te va à décider quelles emissions sont dans quel poste, ou est-ce qu'on va donner le poste dans la réquête ?

**Comment by florianpanchout** [comment]
> Est-ce que tu veux récevoir les clés en format camelCase plutôt que snake_case ? C'est simple à faire à mon coté si oui.

Mon code en front est en camelCase donc ça m'arrangerait de recevoir des variables en camelCase oui, si ça te va aussi :) J'ai l'habitude de travailler avec des back qui font en snake_case donc j'ai écrit comme ça en pensant que c'était une bonne pratique.

> Si il existe déjà un bilan avec l'année et SIREN donnés, est-ce que ça te va de récevoir un 400 ?

Yes 400 avec un code pour me donner plus de précision sur l'erreur, ce serait parfait :) 

> Je pense qu'on n'a pas besoin de inclure l'user dans les données du bilan, parce que le plupart d'utilisateurs verront seulement leur bilans.

Du coup comment tu saurais quels bilans correspondent à quel user ?

> un GET /bilans pour page 4/9 dans le wireframe
> -> /bilans/{id}/emissions

C'est corrigé !

> Est-ce qu'on a besoin des DELETEs pour le bilan et/ou emissions ?

Pour les bilans je dirais non. Vu que l'on exportera vers data.ademe.fr il ne faudrait pas pouvoir supprimer un bilan après sa publication. Ça pose la question de l'édition des bilans d'ailleurs. Pour les emissions oui effectivement. Je le rajoute.

> Ça te va à décider quelles emissions sont dans quel poste, ou est-ce qu'on va donner le poste dans la réquête ?

Je me dis que si le back est agnostique concernant les différents types de sources d'émission, ce serait mieux que je te passe le poste en attribut à la création de la source d'emission (et donc je recevrais ensuite l'ensemble des facteurs et je pourrai faire mon propre tri sur le poste). Je rajoute `poste` dans l'objet emission

**Comment by hfroot** [comment]
Merci pour les réponses !

> Du coup comment tu saurais quels bilans correspondent à quel user ?

Dans le BDD, chaque bilan vont être rélier à un utilisateur avec un foreign key (mais on ne doit pas exposer ça si l'`user` n'est pas utilisé par toi).

> il ne faudrait pas pouvoir supprimer un bilan après sa publication

À quel moment est-ce qu'on publie un bilan ?

**Comment by florianpanchout** [comment]
Lorsque l'on clique sur "Valider mon bilan" sur l'écran 8. Je pose la question de l'édition dans #1

**Comment by hfroot** [comment]
Du coup j'imagine que tu veux avoir le nouveau total après chaque changement des sources d'emission. Alors, est-ce que tu veux recevoir une réponse comme ça pour les actions POST et DELETE ? :
```
{
    "total": (number, selon le poste de la source d'emission),
    "emission": (un objet comme écrit déjà)
}
```

**Comment by hfroot** [comment]
> Pour la liste des sources d'émissions, je me dis qu'il sera peut être intéressant de les calculer via une fonction lambda séparée du back. Ça permettrais d'avoir la liste de tous les facteurs, de leurs unités et des facteurs d'émissions associés dans un fichier json ou markdown, plus simple à éditer pour des personnes non dev.

J'aime bien l'idée de rendrer ça clair à consulter et éditer, est-ce que tu imagine que ça sera des personnes de l'équipe datagir (et pas n'importe quel utilisateur du site) ?
Modifié : je viens de voir https://publi.codes/ utilisé par nosgestesclimat - est-ce que tu imagines qu'on peut utiliser ça peut-être ?

**Comment by florianpanchout** [comment]
Ce serait l'équipe Datagir qui ferait des modifications (au moins dans un premier temps), mais effectivement l'idée serait de rendre l'ensemble des calculs transparents pour tous.

Pas sur que publi.codes soit pertinent ici, on n'utiliserais que 10 % de ses capacités, mais @laem pourra nous confirmer ou infirmer ça

**Comment by laem** [comment]
Pour publi.codes, je pense que le mieux est de tester sur une ébauche de calcul qui ressemblera au résultat final :) 

Voilà [un exemple de micro-simulateur tout bête](https://cutt.ly/rRIQDTi).

Le bac à sable sur publi.codes ne fait que générer la doc. Pour voir une intégration de la doc directement dans une appli React, [exemple ici](https://github.com/laem/empreinte-trottinette/blob/master/src/Calcul.js). 

Pour générer le formulaire, il faut passer au code, exemple [ici](https://github.com/laem/futureco/blob/fv2/source/sites/publicodes/Ferry.tsx#L49) sur une de mes branches de dev très instable.

L'avantage clair est en effet de permettre à des non-dev de comprendre les calculs, notamment via une interface en ligne. 

Mais il faut que les contraintes soient pas vécues comme trop fortes pour une v1 :)

**Comment by florianpanchout** [comment]
@hfroot Comment signaler à l'api qu'un bilan est complet ? 

Côté front, on clique sur "Valider mon bilan". Puis quand je récupère la liste des bilans, je sais s'ils sont complétés si le champ "total" est rempli.

Le calcul du total se faisant côté back (simple addition des postes 1 et 2), est ce que l'on ajoute un endpoint spécifique que le front appelle pour déclencher ce calcul ? Et si oui, quelle url te semble pertinente ?

**Comment by hfroot** [comment]
@florianpanchout qu'est-ce que tu penses d'utiliser un PATCH vers `/bilan` avec un body de `{ statut: "validé" }` ?
Est-ce que la validation d'un bilan est la même chose que la publication d'un bilan ?

**Comment by florianpanchout** [comment]
Ça me va !

Et effectivement, publication est le meilleur terme ici :) Donc plutôt `{ statut: "publié" }`

**Comment by hfroot** [comment]
@florianpanchout champ ajouté

**Comment by florianpanchout** [comment]
Cool merci !

Il me manque les champs 
```
{
    "poste_1": number, // S'incrémente automatiquement à chaque nouvelle source d'émission 
    "poste_2": number, // S'incrémente automatiquement à chaque nouvelle source d'émission 
    "total": number // Calculé à la validation du bilan
}
```
au retour de `/bilans`

Sachant qu'il sera possible de modifier directement `poste_1` et `poste_2` (sans créer de source d'émission).

Pour `total`, vu qu'il s'agira toujours de l'addition de `poste_1` et `poste_2`, ça me va de ne pas l'avoir en back et de le calculer en front si tu préfères.

**Comment by hfroot** [comment]
@florianpanchout champs ajoutés, pour l'instant seulement read-only :) 
qu'est-ce que tu penses d'avoir deux autres champs, `manuel_poste_1` et `manuel_poste_2` ? `poste_x` va retourner alors si le total de resultats d'emissions ou `manuel_poste_x`.
Ça me dérange pas d'ajouter `total` - comme ça on peut avoir un total peut-être plus précise que le somme de `poste_x`s si les resultats d'emission vont avoir plein des décimales (j'imagine qu'on n'aura pas un grand différence)

**Comment by florianpanchout** [comment]
Est ce que c'est utile de différencier avec 2 champs ?

On a deux cas de figure : 
- La personne n'a pas fait son bilan et renseigne des sources d'émissions. On additionne ces sources d'émissions pour calculer `poste_x`
- La personne a déjà fait son bilan ailleurs. Elle ne renseigne pas de source d'émission mais envoie `poste_x` directement

Est ce qu'on ne peut pas mettre comme règle : si des sources émissions sont associées au bilan, `poste_x` est forcement la somme de celles ci. Et on ne prends pas en compte si l'utilisateur essaie de set `poste_x` manuellement.

**Comment by hfroot** [comment]
Il y a un différence légèrement dans le back comment les deux types de champs sont gérés (calculé ou manuel) mais je ne dois pas exposer ce différence au front.

(En plus je pensais que les utilisateurs peuvent jouer avec l'outil en changer son esprit en renseignant le total manuellement après avoir créer quelques émissions, ou vice-versa, et un autre champ donne la liberté a faire ce changement plusieurs fois sans perdre leur travail.)

Si t'es toujours pour, on peut prendre ton règle. En ce cas, est-ce que tu veux que le back donne un réponse statut différent, e.g. 400, si on essaie d'envoyer un `poste_x` quand il y a des émissions associées avec le poste ? L'autre option que je vois c'est un 200 comme normale, mais le `poste_x` retourné va rester le même, le somme de totales d'émissions.

**Comment by florianpanchout** [comment]
Tu soulèves effectivement de bonnes questions au niveau de l'UX. Dans l'idéal il faudrait pouvoir switcher d'un mode à l'autre autant qu'on le souhaite. 

Du coup il faudrait ces attributs : 
`poste_x` : me renvoie soit le total des émissions, soit `manuel_poste_x`, selon le `mode` choisit
`manuel_poste_x` : permet de renseigner manuellement le total d'un poste
`mode` : pour pouvoir changer l'affichage en front

**Comment by hfroot** [comment]
@florianpanchout ces changements sont dispos

**Comment by florianpanchout** [comment]
@hfroot `manuel_poste_x` est limité à 2 décimales. Hors si l'api peut me renvoyer des chiffres à plus de décimales, ça semblerait logique que je puisse en mettre plus ici aussi.

**Comment by hfroot** [comment]
@florianpanchout t'as raison ! Je vais investiguer comment mieux gérer ça

**Comment by hfroot** [comment]
Comme noté en-dessous ici : https://github.com/datagir/bilansclimatsimplifies/issues/6#issuecomment-983763976 je vais arrondir les résultats de chaque émission pour avoir 1 chiffre après le virgule, et les totales comme integers, alors les `manuel_post_x` vont être aussi les integers

**Comment by hfroot** [comment]
@florianpanchout  Les changements API:

Les resultats d'émission sont arrondir au ,1
Les totaux poste et bilan sont arrondir au chiffre entier
Alors manuel_poste_x prend des chiffres entiers aussi.

Il y a de la validation sur la région et NAF: https://github.com/datagir/bilansclimatsimplifies-backend/blob/main/data/region_choices.py https://github.com/datagir/bilansclimatsimplifies-backend/blob/main/data/insee_naf_division_choices.py (les valeurs attendus par le back sont en format "01")

Le fichier EFs https://github.com/datagir/bilansclimatsimplifies-backend/blob/main/data/static/emission-factors.json
- il y a un champ "affichage" pour le nom du type d'émission plus court que le valeur réel attendu par le back (toujours le clé) pour montrer aux utilisateurs
- champ "groupe" avec "Les plus utilisés" ou "" pour poste 1 et "Routier" ou "Non routier" pour poste 2
- les facteurs sont divisés par localisation quand on a des données differentes pour ça. Si une localisation n'est pas donné au back et il y a seulement un choix de localisation, celle-ci sera choisi pour les calcul

Un export privé accessible via GET `/api/v1/export` qui répond avec un CSV.

L'endpoint /auth a été supprimé
Un nouveau endpoint /ademeUser a été créé qui valide le token keycloak reçu et créer/MAJ l'utilisateur dans notre BDD.

Il y a déjà /user, je doit ajouter un champ "is_staff" -> ça indique si l'utilisateur on le droit de téléchargé l'export privé

Je propose que le front n'envoie pas le poste avec l'émission car je peux le retrouver du fichier - qu'est-ce que tu penses ?
