### ISSUE TITLE
Edition / suppression d'un bilan une fois publié

### ISSUE THREAD

**Issue by martinregner** [datagir/bilansclimatsimplifies#7]
Retour de Fanny :

> Sur le principe, je pense effectivement que ce serait mieux qu’on puisse modifier et/ou supprimer un bilan, car on n’est jamais à l’abri d’avoir fait une erreur et qu’on veuille la corriger après coup. Donc **oui pour cette fonctionnalité** (et le **principe de « écrase et remplace »**). Cela ne coincera pas d’un point de vue réglementaire, car in fine, **si l’entreprise supprime son bilan sans en republier un, elle se met dans l’illégalité** à ses risques et périls.

**Comment by florianpanchout** [comment]
@hfroot Il faut du coup ajouter `DELETE` sur `/bilans/:id`

**Comment by hfroot** [comment]
DELETE ajouté. Même les bilans publié et les bilans en brouillon peuvent être supprimé.
